title: Honest Engineering
email: hello@honest.engineering
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://honest.engineering/blog"
github_username:  honestengineering

destination: docs

# Build settings
markdown: kramdown
theme: tale
plugins:
  - jekyll-feed

permalink:  /posts/:title
paginate:   5
